url: "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/JRC-IDEES/JRC-IDEES-2021_v1/"
code_col: "Code"
file_col: "idees_file"
standard_cols: [variable, units, ms, sector, subsector]
units:
replace:
  cells:
    variables:
      Eff: efficiency
      Eff_theor: efficiency_theoretical
      EMIint: emission_intensity
      StockVin: stock_vintage_2020
      TrCap: transport_capacity
      VolCarried: volume_carried
    sectors:
      Tr: transport

  strings:
    variables:
      EMI: emissions
      FEC: final_energy_consumption
      NUM: number
