url: "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/JRC-IDEES/JRC-IDEES-2021_v1/"
years:
  min: 2000
  max: 2050
carriers:
  - Gasoline
  - BioGasoline
  - Diesel oil
  - BioDiesel oil
  - Electricity
  - LPG
  - Natural Gas
  - BioNatural Gas
